spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_cinema?characterEncoding=utf-8&useSSL=false
    username: root
    password: 113797
  application:
    name: movie-server
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    port: 6379
    host: 111.229.91.143

management:
  endpoints:
    web:
      exposure:
        include: "*"

#    开启sql语句日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8888
  servlet:
    context-path: /movie

rocketmq:
  name-server: 111.229.91.143:9876
  producer:
    group: movie

